# Generated by Django 2.2.1 on 2019-05-07 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190507_1305'),
        ('api', '0003_auto_20190507_1147'),
    ]

    operations = [
    ]
