# Generated by Django 2.2.1 on 2019-05-07 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20190507_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Article'),
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
